const products = [
    { id: 1, name: "Салат Цезарь с курицей", category: "ready-food", price: 450, image: "img/111.png", brand: "Ресторанный дворик", weight: "350 г", description: "Свежий салат с куриной грудкой, листьями айсберг, пармезаном, крутонами и классическим соусом Цезарь." },
    { id: 2, name: "Пельмени говяжьи", category: "ready-food", price: 320, image: "img/2.png", brand: "Цезарь", weight: "500 г", description: "Традиционные пельмени с говяжьим фаршем, приготовленные по классическому рецепту. Идеально с маслом и сметаной." },
    { id: 3, name: "Борщ украинский", category: "ready-food", price: 280, image: "img/3.png", brand: "Домашняя кухня", weight: "500 г", description: "Наваристый борщ со свеклой, капустой и говядиной." },
    { id: 4, name: "Лазанья с мясом", category: "ready-food", price: 390, image: "img/4.png", brand: "Итальянская", weight: "400 г", description: "Классическая итальянская лазанья с мясным фаршем, соусом бешамель и сыром моцарелла." },
    { id: 5, name: "Суши сет Калифорния", category: "ready-food", price: 520, image: "img/5.png", brand: "Tokyo Express", weight: "20 шт.", description: "20 роллов Калифорния с крабом, авокадо и огурцом." },
    { id: 6, name: "Пицца Маргарита", category: "ready-food", price: 270, image: "img/6.png", brand: "Zotman pizza", weight: "30 см", description: "Классическая итальянская пицца с томатным соусом, сыром моцарелла и свежим базиликом." },
    { id: 7, name: "Крылышки BBQ", category: "ready-food", price: 510, image: "img/7.png", brand: "BBQ Master", weight: "500 г", description: "Куриные крылышки в фирменном соусе барбекю с хрустящей корочкой." },
    { id: 8, name: "Голубцы с мясом", category: "ready-food", price: 240, image: "img/8.png", brand: "Домашние", weight: "400 г", description: "Голубцы из капустных листьев с мясным фаршем и рисом в томатном соусе." },
    { id: 9, name: "Шоколад молочный", category: "sweets", price: 250, image: "img/9.png", brand: "Алёнка", weight: "100 г", description: "Молочный шоколад. Идеально для перекуса или десерта." },
    { id: 10, name: "Торт Наполеон", category: "sweets", price: 1200, image: "img/10.png", brand: "Вкусный дом", weight: "1 кг", description: "Классический торт Наполеон с нежным заварным кремом. Идеальный десерт для праздника." },
    { id: 11, name: "Конфеты Ассорти", category: "sweets", price: 500, image: "img/11.png", brand: "Красный Октябрь", weight: "250 г", description: "Набор шоколадных конфет с различными начинками: пралине, грильяж, суфле." },
    { id: 12, name: "Пирожное Эклер", category: "sweets", price: 180, image: "img/12.png", brand: "Пирожковая", weight: "2 шт.", description: "Эклеры с нежным заварным кремом, покрытые глазурью. Идеальный десерт к кофе." },
    { id: 13, name: "Зефир белый", category: "sweets", price: 95, image: "img/13.png", brand: "Шармэль", weight: "200 г", description: "Ванильный зефир нежной консистенции. Без искусственных красителей." },
    { id: 14, name: "Мармелад фруктовый", category: "sweets", price: 110, image: "img/14.png", brand: "Fruittella", weight: "150 г", description: "Жевательный мармелад с натуральными фруктовыми соками. Разноцветные змейки." },
    { id: 15, name: "Пряник", category: "sweets", price: 75, image: "img/15.png", brand: "Тульские", weight: "300 г", description: "Ароматный пряник с начинкой. Идеальны к чаю." },
    { id: 16, name: "Вафли с шоколадом", category: "sweets", price: 140, image: "img/16.png", brand: "Artek", weight: "200 г", description: "Хрустящие вафли с шоколадной начинкой. Отличный перекус." },
    { id: 17, name: "Яблоки Голден", category: "vegetables", price: 180, image: "img/17.png", brand: "Фермерские", weight: "1 кг", description: "Сладкие яблоки сорта Голден. Идеальны для еды в сыром виде и для выпечки." },
    { id: 18, name: "Бананы", category: "vegetables", price: 90, image: "img/18.png", brand: "Эквадор", weight: "1 кг", description: "Спелые бананы. Богаты калием, идеальны для завтрака и перекуса." },
    { id: 19, name: "Клубника свежая", category: "vegetables", price: 320, image: "img/19.png", brand: "Краснодарский край", weight: "500 г", description: "Свежая клубника сладких сортов. Идеальна для десертов и употребления в свежем виде." },
    { id: 20, name: "Помидоры черри", category: "vegetables", price: 200, image: "img/20.png", brand: "Азербайджан", weight: "500 г", description: "Сладкие помидоры черри. Отлично подходят для салатов и украшения блюд." },
    { id: 21, name: "Огурцы грунтовые", category: "vegetables", price: 55, image: "img/21.png", brand: "Тепличные", weight: "1 кг", description: "Свежие огурцы с хрустящей мякотью. Идеальны для салатов." },
    { id: 22, name: "Картофель молодой", category: "vegetables", price: 45, image: "img/22.png", brand: "Беларусь", weight: "1 кг", description: "Молодой картофель с тонкой кожицей. Отлично подходит для варки и запекания." },
    { id: 23, name: "Морковь свежая", category: "vegetables", price: 120, image: "img/23.png", brand: "Органическая", weight: "1 кг", description: "Сладкая морковь. Богата витаминами, подходит для салатов и горячих блюд." },
    { id: 24, name: "Лук репчатый", category: "vegetables", price: 95, image: "img/24.png", brand: "Репчатый", weight: "1 кг", description: "Золотистый репчатый лук. Основной ингредиент для многих блюд." },
    { id: 25, name: "Брокколи", category: "vegetables", price: 180, image: "img/25.png", brand: "Свежий урожай", weight: "500 г", description: "Свежая брокколи. Богата витаминами, идеальна для здорового питания." },
    { id: 26, name: "Зелень укропа", category: "vegetables", price: 40, image: "img/26.png", brand: "Свежая зелень", weight: "100 г", description: "Свежий укроп. Ароматная зелень для салатов, супов и вторых блюд." },
    { id: 27, name: "Петрушка кудрявая", category: "vegetables", price: 50, image: "img/27.png", brand: "Свежая зелень", weight: "100 г", description: "Свежая петрушка. Богата витаминами, отлично дополняет любые блюда." },
    { id: 28, name: "Авокадо Хасс", category: "vegetables", price: 280, image: "img/28.png", brand: "Перу", weight: "1 кг", description: "Спелые авокадо сорта Хасс. Идеальны для салатов, тостов и гуакамоле." },
    { id: 29, name: "Виноград Кишмиш", category: "vegetables", price: 210, image: "img/29.png", brand: "Молдова", weight: "1 кг", description: "Сладкий виноград без косточек. Отлично подходит для перекуса и десертов." },
    { id: 30, name: "Курица охлажденная", category: "meat", price: 650, image: "img/30.png", brand: "Петелинка", weight: "1.5 кг", description: "Целая курица охлажденная. Идеальна для супов, запекания и жарки." },
    { id: 31, name: "Говядина вырезка", category: "meat", price: 890, image: "img/31.png", brand: "Мираторг", weight: "1 кг", description: "Свежая говяжья вырезка. Нежное мясо для стейков и ростбифов." },
    { id: 32, name: "Свинина лопатка", category: "meat", price: 750, image: "img/32.png", brand: "Черкизово", weight: "1 кг", description: "Свежая свиная лопатка. Отлично подходит для жарки, тушения и шашлыка." },
    { id: 33, name: "Фарш говяжий", category: "meat", price: 280, image: "img/33.png", brand: "Мясной ряд", weight: "500 г", description: "Свежий говяжий фарш. Идеален для котлет, тефтелей и фаршированных блюд." },
    { id: 34, name: "Колбаса докторская", category: "meat", price: 320, image: "img/34.png", brand: "Царь-мясо", weight: "500 г", description: "Вареная колбаса высшего сорта. Отлично подходит для бутербродов и салатов." },
    { id: 35, name: "Бекон копченый", category: "meat", price: 450, image: "img/35.png", brand: "Свинокомплекс", weight: "300 г", description: "Копченый бекон тонкой нарезки. Идеален для завтраков и сэндвичей." },
    { id: 36, name: "Сосиски молочные", category: "meat", price: 180, image: "img/36.png", brand: "Микоян", weight: "500 г", description: "Детские сосиски высшего сорта. Быстро и вкусно." },
    { id: 37, name: "Молоко 3.2%", category: "dairy", price: 95, image: "img/37.png", brand: "Простоквашино", weight: "1 л", description: "Пастеризованное молоко. Идеально для каш, кофе и выпечки." },
    { id: 38, name: "Сыр Гауда", category: "dairy", price: 420, image: "img/38.png", brand: "Гауда", weight: "500 г", description: "Голландский сыр Гауда с нежным вкусом. Отлично для бутербродов и салатов." },
    { id: 39, name: "Йогурт греческий", category: "dairy", price: 85, image: "img/39.png", brand: "Активиа", weight: "400 г", description: "Натуральный греческий йогурт без добавок. Богат белком." },
    { id: 40, name: "Творог 5%", category: "dairy", price: 120, image: "img/40.png", brand: "Домик в деревне", weight: "500 г", description: "Обезжиренный творог. Отлично подходит для завтрака и выпечки." },
    { id: 41, name: "Сметана 15%", category: "dairy", price: 75, image: "img/41.png", brand: "Вкуснотеево", weight: "400 г", description: "Домашняя сметана. Идеальна для супов, салатов и десертов." },
    { id: 42, name: "Кефир 2.5%", category: "dairy", price: 80, image: "img/42.png", brand: "Чабан", weight: "1 л", description: "Биокефир с живыми бактериями. Полезен для пищеварения." },
    { id: 43, name: "Масло сливочное", category: "dairy", price: 220, image: "img/43.png", brand: "Вкуснотеево", weight: "200 г", description: "Сливочное масло 82.5% жирности. Идеально для выпечки и бутербродов." },
    { id: 44, name: "Сливки 23%", category: "dairy", price: 160, image: "img/44.png", brand: "Пармалат", weight: "500 мл", description: "Сливки для взбивания. Идеальны для десертов и соусов." },
    { id: 45, name: "Ряженка", category: "dairy", price: 90, image: "img/45.png", brand: "Вкуснотеево", weight: "1 л", description: "Традиционная ряженка. Нежный вкус и полезные свойства." },
    { id: 46, name: "Яйца куриные С0", category: "dairy", price: 120, image: "img/46.png", brand: "Роскар", weight: "10 шт.", description: "Отборные куриные яйца высшей категории. Идеальны для завтрака и выпечки." },
    { id: 47, name: "Хлеб Бородинский", category: "bakery", price: 65, image: "img/47.png", brand: "Хлебный дом", weight: "500 г", description: "Ржаной хлеб с тмином и кориандром. Ароматный и полезный." },
    { id: 48, name: "Батон нарезной", category: "bakery", price: 45, image: "img/48.png", brand: "Каравай", weight: "400 г", description: "Пшеничный батон нарезной. Мягкий и свежий." },
    { id: 49, name: "Булочки сдобные", category: "bakery", price: 85, image: "img/49.png", brand: "Пекарня", weight: "2 шт.", description: "Сахарные булочки с посыпкой. Идеальны к чаю." },
    { id: 50, name: "Круассан с шоколадом", category: "bakery", price: 120, image: "img/50.png", brand: "French Bakery", weight: "150 г", description: "Слоеный круассан с шоколадной начинкой. Французская классика." },
    { id: 51, name: "Пончики глазированные", category: "bakery", price: 75, image: "img/51.png", brand: "Криспи Крим", weight: "4 шт.", description: "Пончики с сахарной глазурью. Мягкие и сладкие." },
    { id: 52, name: "Пирог с яблоками", category: "bakery", price: 280, image: "img/52.png", brand: "Домашний", weight: "800 г", description: "Домашний пирог с яблочной начинкой. Идеальный десерт." },
    { id: 53, name: "Лосось свежий", category: "fish", price: 1200, image: "img/53.png", brand: "Норвегия", weight: "1 кг", description: "Филе свежего лосося. Идеально для запекания и стейков." },
    { id: 54, name: "Форель радужная", category: "fish", price: 950, image: "img/54.png", brand: "Русское море", weight: "1 кг", description: "Свежая форель. Нежная рыба с минимальным количеством костей." },
    { id: 55, name: "Креветки тигровые", category: "fish", price: 850, image: "img/55.png", brand: "Вкус моря", weight: "500 г", description: "Очищенные тигровые креветки. Отлично для пасты, салатов и гриля." },
    { id: 56, name: "Кальмар замороженный", category: "fish", price: 420, image: "img/56.png", brand: "Океан", weight: "500 г", description: "Тушки кальмара. Идеальны для салатов, жарки и фарширования." },
    { id: 57, name: "Сельдь соленая", category: "fish", price: 180, image: "img/57.png", brand: "Исландия", weight: "500 г", description: "Филе соленой сельди. Классика русской кухни." },
    { id: 58, name: "Сок апельсиновый", category: "beverages", price: 120, image: "img/58.png", brand: "Добрый", weight: "1 л", description: "100% апельсиновый сок без добавок. Богат витамином C." },
    { id: 59, name: "Вода минеральная", category: "beverages", price: 65, image: "img/59.png", brand: "Псыж", weight: "1.5 л", description: "Газированная минеральная вода. Освежающая и утоляющая жажду." },
    { id: 60, name: "Чай черный", category: "beverages", price: 180, image: "img/60.png", brand: "Greenfield", weight: "100 пак.", description: "Цейлонский черный чай в пакетиках. Ароматный и бодрящий." },
    { id: 61, name: "Кофе молотый", category: "beverages", price: 350, image: "img/61.png", brand: "Нескафе Голд", weight: "250 г", description: "Арабика 100% средней обжарки. Идеален для утреннего кофе." },
    { id: 62, name: "Лимонад натуральный", category: "beverages", price: 95, image: "img/62.png", brand: "Черноголовка", weight: "1 л", description: "Газированный лимонад с натуральным лимонным соком." },
    { id: 63, name: "Морс клюквенный", category: "beverages", price: 110, image: "img/63.png", brand: "Сады Придонья", weight: "1 л", description: "Натуральный клюквенный морс без консервантов." },
    { id: 64, name: "Квас хлебный", category: "beverages", price: 150, image: "img/64.png", brand: "Царские припасы", weight: "1 л", description: "Натуральный хлебный квас. Традиционный русский напиток." },
    { id: 65, name: "Энергетик", category: "beverages", price: 85, image: "img/65.png", brand: "Adrenaline Rush", weight: "0.5 л", description: "Энергетический напиток без сахара. Бодрит и освежает." },
    { id: 66, name: "Рис басмати", category: "grocery", price: 95, image: "img/66.png", brand: "Мистраль", weight: "1 кг", description: "Длиннозерный рис басмати. Рассыпчатый и ароматный." },
    { id: 67, name: "Гречка ядрица", category: "grocery", price: 85, image: "img/67.png", brand: "Мистраль", weight: "1 кг", description: "Отборная гречневая крупа. Богата железом и витаминами." },
    { id: 68, name: "Макароны спагетти", category: "grocery", price: 65, image: "img/68.png", brand: "Barilla", weight: "500 г", description: "Спагетти из твердых сортов пшеницы. Идеальны для итальянских блюд." },
    { id: 69, name: "Фасоль консервированная", category: "grocery", price: 75, image: "img/69.png", brand: "Бондюэль", weight: "400 г", description: "Фасоль в томатном соусе. Готова к употреблению." },
    { id: 70, name: "Овсяные хлопья", category: "grocery", price: 55, image: "img/70.png", brand: "Nordic", weight: "500 г", description: "Овсяные хлопья быстрого приготовления. Идеальны для здорового завтрака." },
    { id: 71, name: "Мука пшеничная", category: "grocery", price: 45, image: "img/71.png", brand: "Макфа", weight: "1 кг", description: "Пшеничная мука высшего сорта. Для выпечки и кулинарии." },
    { id: 72, name: "Сахар песок", category: "grocery", price: 65, image: "img/72.png", brand: "Русский сахар", weight: "1 кг", description: "Белый сахарный песок. Для чая, кофе и выпечки." },
    { id: 73, name: "Соль йодированная", category: "grocery", price: 25, image: "img/73.png", brand: "Морская", weight: "1 кг", description: "Мелкая йодированная соль. Обогащена йодом для здоровья." },
    { id: 74, name: "Масло подсолнечное", category: "grocery", price: 110, image: "img/74.png", brand: "Altero", weight: "1 л", description: "Рафинированное подсолнечное масло. Без запаха, для жарки и салатов." },
    { id: 75, name: "Томатная паста", category: "grocery", price: 55, image: "img/75.png", brand: "Помидорка", weight: "200 г", description: "Томатная паста 30% сухих веществ. Для соусов и супов." },
    { id: 76, name: "Мед цветочный", category: "grocery", price: 180, image: "img/76.png", brand: "Башкирский", weight: "500 г", description: "Натуральный цветочный мед. Полезный и ароматный." },
    { id: 77, name: "Уксус яблочный", category: "grocery", price: 95, image: "img/77.png", brand: "Столовый", weight: "500 мл", description: "Яблочный уксус 6%. Для маринадов и салатов." },
    { id: 78, name: "Горчица столовая", category: "grocery", price: 120, image: "img/78.png", brand: "Махеевъ", weight: "200 г", description: "Острая столовая горчица. Для мясных блюд и бутербродов." },
    { id: 79, name: "Майонез Провансаль", category: "grocery", price: 85, image: "img/79.png", brand: "Московский", weight: "400 г", description: "Майонез 67% жирности. Классический провансаль." },
    { id: 80, name: "Пельмени замороженные", category: "frozen", price: 320, image: "img/80.png", brand: "Сибирская коллекция ", weight: "1 кг", description: "Замороженные пельмени с говяжьим фаршем. Быстро и вкусно." },
    { id: 81, name: "Овощная смесь", category: "frozen", price: 180, image: "img/81.png", brand: "4 сезона", weight: "800 г", description: "Замороженная мексиканская смесь овощей. Для рагу и гарниров." },
    { id: 82, name: "Ягоды ассорти", category: "frozen", price: 350, image: "img/82.png", brand: "Свой урожай", weight: "1 кг", description: "Смесь замороженных ягод: клубника, малина, смородина." },
    { id: 83, name: "Блинчики с мясом", category: "frozen", price: 280, image: "img/83.png", brand: "С пылу С жару", weight: "500 г", description: "Замороженные блинчики с мясной начинкой. Быстрый ужин." },
    { id: 84, name: "Пицца замороженная", category: "frozen", price: 420, image: "img/84.png", brand: "Zotman", weight: "400 г", description: "Замороженная пицца Пепперони. Готовится за 15 минут." },
    { id: 85, name: "Картофель фри", category: "frozen", price: 190, image: "img/85.png", brand: "Макси", weight: "1 кг", description: "Замороженный картофель фри. Для жарки во фритюре." },
    { id: 86, name: "Креветки королевские", category: "frozen", price: 650, image: "img/86.png", brand: "Королевские", weight: "500 г", description: "Замороженные королевские креветки. Крупные и вкусные." },
    { id: 87, name: "Тесто слоеное", category: "frozen", price: 320, image: "img/87.png", brand: "Хлебный дом", weight: "500 г", description: "Замороженное слоеное тесто. Для выпечки и десертов." },
    { id: 88, name: "Пюре яблочное", category: "baby", price: 85, image: "img/88.png", brand: "Агуша", weight: "100 г", description: "Яблочное пюре для детей с 4 месяцев. Без сахара и консервантов." },
    { id: 89, name: "Каша молочная", category: "baby", price: 120, image: "img/89.png", brand: "Агуша", weight: "200 г", description: "Рисовая молочная каша для детей. Обогащена витаминами." },
    { id: 90, name: "Смесь питательная", category: "baby", price: 950, image: "img/90.png", brand: "Nutrilon", weight: "800 г", description: "Детская молочная смесь для детей 0-6 месяцев." },
    { id: 91, name: "Печенье детское", category: "baby", price: 75, image: "img/91.png", brand: "Фрутоняня", weight: "180 г", description: "Печенье для прорезывания зубов. Растворяется во рту." },
    { id: 92, name: "Сок детский", category: "baby", price: 65, image: "img/92.png", brand: "Фрутоняня", weight: "200 мл", description: "Яблочный сок для детей. Без сахара и консервантов." },
    { id: 93, name: "Хлеб безглютеновый", category: "healthy", price: 180, image: "img/93.png", brand: "ВВ", weight: "300 г", description: "Хлеб без глютена на рисовой муке. Для аллергиков." },
    { id: 94, name: "Молоко миндальное", category: "healthy", price: 220, image: "img/94.png", brand: "Planto", weight: "1 л", description: "Миндальное молоко без лактозы. Для веганов и аллергиков." },
    { id: 95, name: "Паста из нута", category: "healthy", price: 190, image: "img/95.png", brand: "ВВ", weight: "300 г", description: "Хумус классический. Богат белком и клетчаткой." },
    { id: 96, name: "Батончики протеиновые", category: "healthy", price: 150, image: "img/96.png", brand: "FitKit", weight: "5 шт.", description: "Протеиновые батончики с шоколадом. Для спортсменов." },
    { id: 97, name: "Смесь ореховая", category: "healthy", price: 320, image: "img/97.png", brand: "Ореховая ферма", weight: "500 г", description: "Смесь 5 видов орехов. Без соли и масла." },
    { id: 98, name: "Масло кокосовое", category: "healthy", price: 450, image: "img/98.png", brand: "BioLife", weight: "500 мл", description: "Органическое кокосовое масло. Для жарки и косметики." },
    { id: 99, name: "Семена чиа", category: "healthy", price: 280, image: "img/99.png", brand: "Superfood", weight: "500 г", description: "Органические семена чиа. Богаты омега-3." },
    { id: 100, name: "Тофу соевый", category: "healthy", price: 180, image: "img/100.png", brand: "ВВ", weight: "400 г", description: "Соевый творог тофу. Источник растительного белка." }
];

// Экспортируем в глобальную область видимости
window.products = products;
console.log('Data.js: Загружено', products.length, 'товаров');